/**
 * Spawns Captora's Next.js standalone server as a child process and
 * waits for it to be ready before resolving. The Electron main process
 * uses the resolved port to load the BrowserWindow.
 *
 * In dev mode (NODE_ENV=development) we don't spawn anything and
 * assume the developer is already running `npm run dev:web` on
 * localhost:3000 — `npm run dev:electron` will just open the window
 * pointing at that.
 *
 * In packaged mode the Next.js standalone bundle is shipped under
 * `<resources>/web/.next/standalone/`. We pass it the env vars that
 * activate desktop-mode behaviour in `/api/transcribe` and `/api/render`:
 *
 *   CAPTORA_MODE=desktop
 *   CAPTORA_SESSIONS_DIR=<userData>/sessions
 *   CAPTORA_RENDERS_DIR=<userData>/renders
 *
 * No code in `web/` knows we're inside Electron — it just sees these
 * env vars and switches paths accordingly.
 */

import { spawn, ChildProcess } from "child_process";
import { mkdir, readFile } from "fs/promises";
import { existsSync, appendFileSync, createWriteStream } from "fs";
import { join } from "path";
import { app } from "electron";
import { capabilitiesToEnv, loadOrDetectCapabilities } from "./capabilities";
import { recordEvent } from "./eventSpool";

/**
 * Synchronous one-shot log line. Used for the diagnostic startup
 * banner so it's guaranteed flushed to disk before anything else
 * runs — async WriteStreams sometimes lose their initial writes if
 * the process crashes shortly after.
 */
function logSync(message: string): void {
  try {
    const path = join(app.getPath("userData"), "captora.log");
    appendFileSync(path, message);
  } catch {
    // userData may not be writable in weird sandbox configs — ignore
  }
}

/**
 * Tiny .env parser — handles `KEY=VALUE` lines, ignores blanks/comments.
 * Avoids pulling in `dotenv` as a dep just for this. Strips matching
 * surrounding quotes so values like `KEY="some value"` work.
 */
async function loadEnvFile(path: string): Promise<Record<string, string>> {
  if (!existsSync(path)) return {};
  const out: Record<string, string> = {};
  const raw = await readFile(path, "utf8");
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

const isDev = process.env.NODE_ENV === "development";

let serverProcess: ChildProcess | null = null;

/** Set by stopNextServer() so the exit handler can tell a clean shutdown
 *  apart from a crash. Without it, every normal app quit would be
 *  reported as a server crash. */
let stoppingIntentionally = false;

interface ServerInfo {
  port: number;
  url: string;
}

/** Pick an available TCP port ≥ 3100 so we don't fight a user's existing
 *  Next.js dev server on 3000. Falls back through 50 ports before giving up. */
async function findFreePort(start = 3100): Promise<number> {
  const net = await import("net");
  for (let port = start; port < start + 50; port++) {
    const free = await new Promise<boolean>((resolve) => {
      const srv = net.createServer();
      srv.once("error", () => resolve(false));
      srv.once("listening", () => srv.close(() => resolve(true)));
      srv.listen(port, "127.0.0.1");
    });
    if (free) return port;
  }
  throw new Error("No free port in 3100..3149");
}

export async function startNextServer(): Promise<ServerInfo> {
  // Dev mode: developer is running `npm run dev:web` separately. Skip
  // spawning anything; just point the window at their dev server.
  if (isDev) {
    return { port: 3000, url: "http://127.0.0.1:3000" };
  }

  const userData = app.getPath("userData");
  const sessionsDir = join(userData, "sessions");
  const rendersDir = join(userData, "renders");
  await mkdir(sessionsDir, { recursive: true });
  await mkdir(rendersDir, { recursive: true });

  const port = await findFreePort();
  const standaloneDir = join(
    process.resourcesPath,
    "web",
    ".next",
    "standalone"
  );
  const serverScript = join(standaloneDir, "web", "server.js");

  // Load the bundled production env file (Supabase URL/key, Groq key,
  // initial-prompt vocabulary, etc.). Generated by GitHub Actions from
  // repo Secrets at build time — never lives in the source tree, never
  // committed. Missing file is non-fatal (dev mode, manual builds);
  // server-side calls just lose access to those keys.
  const envFilePath = join(process.resourcesPath, "web", ".env.production");
  const fileEnv = await loadEnvFile(envFilePath);
  const fileEnvKeyCount = Object.keys(fileEnv).length;
  if (fileEnvKeyCount > 0) {
    console.log(`[nextServer] loaded ${fileEnvKeyCount} keys from bundled .env.production`);
  } else {
    console.warn(`[nextServer] no .env.production found at ${envFilePath} — cloud transcription will not work`);
  }

  // Detect (or load cached) machine capabilities — Python presence,
  // faster-whisper install, GPU, internet. Used to suppress paths that
  // would otherwise spam errors per-transcription on machines that don't
  // have Python installed (most non-dev installs). Cached for 7 days
  // and re-probed on Captora upgrades.
  const capabilities = await loadOrDetectCapabilities();
  const capabilityEnv = capabilitiesToEnv(capabilities);
  if (Object.keys(capabilityEnv).length > 0) {
    console.log(
      `[nextServer] capability-driven env overrides: ${Object.keys(capabilityEnv).join(", ")}`
    );
  }

  console.log(`[nextServer] spawning ${serverScript} on port ${port}`);

  serverProcess = spawn(process.execPath, [serverScript], {
    cwd: standaloneDir,
    env: {
      ...process.env,
      // Bundled production keys — apply BEFORE the runtime overrides
      // below so a value in the env file can't accidentally override
      // CAPTORA_MODE / paths.
      ...fileEnv,
      // Capability overrides — applied AFTER fileEnv so a missing
      // Python installation on the user's machine reliably disables
      // FASTER_WHISPER_ENABLED even if .env.production says =1.
      ...capabilityEnv,
      // CRITICAL: tells Electron to run as Node.js when invoked with a
      // script arg. Without this, `process.execPath` (which is the
      // Electron binary inside the packaged app) tries to launch as a
      // normal Electron app and exits with code 0 — leaving the user
      // staring at "Next.js exited early with code 0".
      ELECTRON_RUN_AS_NODE: "1",
      NODE_ENV: "production",
      PORT: String(port),
      HOSTNAME: "127.0.0.1",
      // Desktop-mode flags consumed by web/src/lib/captora-mode.ts
      CAPTORA_MODE: "desktop",
      CAPTORA_SESSIONS_DIR: sessionsDir,
      CAPTORA_RENDERS_DIR: rendersDir,
    },
    stdio: ["ignore", "pipe", "pipe"],
  });

  // Mirror stdout/stderr to a log file in userData so users can hand
  // us logs when something breaks. Sync writes for the startup banner
  // (guaranteed flushed even if the process crashes seconds later);
  // async WriteStream for the high-volume per-line piping.
  // Location: %APPDATA%/Captora/captora.log
  const logPath = join(app.getPath("userData"), "captora.log");
  logSync(`\n--- Captora v${app.getVersion()} launched ${new Date().toISOString()} ---\n`);
  logSync(`[nextServer] envFilePath=${envFilePath} fileEnvKeys=${fileEnvKeyCount}\n`);
  logSync(`[nextServer] standaloneDir=${standaloneDir}\n`);
  logSync(`[nextServer] serverScript=${serverScript}\n`);
  logSync(`[nextServer] sessionsDir=${sessionsDir}\n`);
  logSync(`[nextServer] rendersDir=${rendersDir}\n`);
  logSync(`[nextServer] port=${port}\n`);

  const logStream = createWriteStream(logPath, { flags: "a" });

  serverProcess.stdout?.on("data", (chunk: Buffer) => {
    process.stdout.write(`[next] ${chunk}`);
    logStream.write(`[next] ${chunk}`);
  });
  serverProcess.stderr?.on("data", (chunk: Buffer) => {
    process.stderr.write(`[next-err] ${chunk}`);
    logStream.write(`[next-err] ${chunk}`);
  });

  // Wait for the "Ready" line on stdout — Next.js prints it once it's
  // listening. 30s timeout; first launch can be slow on cold disk.
  await new Promise<void>((resolve, reject) => {
    const timer = setTimeout(() => {
      reject(new Error("Next.js failed to start within 30s"));
    }, 30_000);

    serverProcess?.stdout?.on("data", (chunk: Buffer) => {
      if (chunk.toString().toLowerCase().includes("ready")) {
        clearTimeout(timer);
        resolve();
      }
    });
    serverProcess?.on("error", (err) => {
      clearTimeout(timer);
      reject(err);
    });
    serverProcess?.on("exit", (code) => {
      clearTimeout(timer);
      reject(new Error(`Next.js exited early with code ${code}`));
    });
  });

  // Past this point the server is up. If it dies LATER — OOM during a
  // 4K render, a crash inside Remotion, the OS killing it — the window
  // stays open showing a page that can no longer reach its backend, and
  // every subsequent action fails with an opaque network error. That
  // looked identical to "the app is broken" from the user's side and
  // left no trace anywhere we could see.
  //
  // `stoppingIntentionally` keeps a normal app quit from being reported
  // as a crash.
  serverProcess.on("exit", (code, signal) => {
    if (stoppingIntentionally) return;
    const detail = `Embedded Next.js server exited unexpectedly (code=${code} signal=${signal})`;
    logSync(`[nextServer] ${detail}\n`);
    recordEvent("main.next-server-exited", detail, {
      context: { code, signal, port, phase: "running" },
    });
  });

  return { port, url: `http://127.0.0.1:${port}` };
}

/** Kill the embedded Next.js server. Called on app quit so the process
 *  doesn't linger after the window closes. */
export function stopNextServer(): void {
  stoppingIntentionally = true;
  if (serverProcess && !serverProcess.killed) {
    serverProcess.kill();
    serverProcess = null;
  }
}
